tools:
    sensiolabs_security_checker: true
    php_cpd:
        enabled: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
            tab_width: 4
    php_cs_fixer:
        enabled: true
        config:
            level: all
            fixers:
                indentation: true
    php_mess_detector:
        enabled: true
    php_analyzer:
        enabled: true
        config:
            use_statement_fixes:
                order_alphabetically: true
    php_loc: true
    php_pdepend:
        enabled: true

filter:
    excluded_paths:
        - "vendor/"
        - "app/"
        - "web/"
        - "var/"
        - "tests/"
        - "*/Tests/*"

build:
    environment:
        php:
            version: 7.0.8
    dependencies:
        before:
            - mysql -e 'create database votingsystem;'
    tests:
        before:
            - bin/console doctrine:migrations:migrate --no-interaction
        override:
            -
                command: 'phpunit --coverage-clover=some-file'
                coverage:
                    file: 'some-file'
                    format: 'clover'

changetracking:
    bug_patterns: ["\bfix(?:es|ed)?\b", "\b\\[(?:bug|fix)\\]\b"]
    feature_patterns: ["\badd(?:s|ed)?\b", "\bimplement(?:s|ed)?\b", "\b\\[(?:improvement|feature)\\]\b"]
