tools:
    sensiolabs_security_checker: true
    php_cpd:
        enabled: true
        excluded_dirs: [web/app*, var/*]
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
            tab_width: 4
        filter:
            excluded_paths: [app/*, var/*]
    php_cs_fixer:
        enabled: true
        config:
            level: all
            fixers:
                indentation: true
        filter:
            excluded_paths: [app/*, var/*]
    php_mess_detector:
        filter:
            excluded_paths: [app/*, var/*]
        enabled: true
    php_analyzer:
        enabled: true
        filter:
            excluded_paths: [app/*, var/*]
        config:
            use_statement_fixes:
                order_alphabetically: true
    php_loc: true
    php_pdepend:
        excluded_dirs:
            [vendor/*, app/*, var/*]
        enabled: true

build:
    environment:
        php:
            version: 7.0

changetracking:
    bug_patterns: ["\bfix(?:es|ed)?\b", "\b\\[(?:bug|fix)\\]\b"]
    feature_patterns: ["\badd(?:s|ed)?\b", "\bimplement(?:s|ed)?\b", "\b\\[(?:improvement|feature)\\]\b"]
