language: php
matrix:
  include:
    - php: 7.0
    - php: nightly
  allow_failures:
    - php: nightly

env:
  - DB=mysql

install:
  - sudo apt-get update
  - travis_retry sudo apt-get install parallel

before_script:
  - phpenv rehash
  - mysql -e 'create database symfony;'
  - composer install

script:
  - bin/phpunit
  - find . -path ./vendor -prune -o -type f -name "*.php" | parallel --gnu --keep-order 'php -l {} > /dev/null' || exit 1
  - php bin/console lint:twig @AppBundle
