language: php

php:
    - 7.0
    - nightly
matrix:
  allow_failures:
    - php: nightly

env:
  - DB=mysql

install:
  - sudo apt-get update
  - travis_retry sudo apt-get install parallel

before_script:
  - phpenv rehash
  - mysql -e 'create database votingsystem;'
  - composer install
  - bin/console doctrine:migrations:migrate --no-interaction

script:
  - bin/phpunit
  - find . -path ./vendor -prune -o -type f -name "*.php" | parallel --gnu --keep-order 'php -l {} > /dev/null' || exit 1
  - php bin/console lint:twig @AppBundle
