<?php

namespace AppBundle\Repository;

/**
 * PollRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollRepository extends \Doctrine\ORM\EntityRepository
{
}
