<?php

namespace AppBundle\Repository;

/**
 * PollTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
