services:
  app.poll_manager:
    class:  AppBundle\Utils\PollManager
    arguments: ["@doctrine", "@app.election_manager"]

  app.election_manager:
    class:  AppBundle\Utils\ElectionManager
    arguments: ["@doctrine"]

  app.controller.vote_controller:
      class: AppBundle\Controller\VoteController
      arguments: ['@app.poll_manager', '@app.election_manager']
      calls:
          - [setContainer, ['@service_container']]